name: Generate Async code

on: push

permissions: {}

jobs:
  generate-async:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 2.2.*

    - name: Generate Async code
      run: |
        dotnet restore "./Tools/packages.csproj" --packages ./Tools
        pushd src
        dotnet restore ./NHibernate.sln /p:TreatWarningsAsErrors=false
        dotnet $(find ./../Tools/csharpasyncgenerator.commandline -name AsyncGenerator.CommandLine.dll) 
        popd

    - name: Push changes
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            exit 0
        fi
        git add -A
        git commit -am "Generate async files"
        git push
