name: .NET Core

on: [push, pull_request]

jobs:
  db:
    strategy:
      fail-fast: false
      matrix:
        config: |
          [
          {DB: SqlServer2008, 
          CONNECTION_STRING: "Server=localhost;initial catalog=nhibernate;User Id=sa;Password=P@ssw0rd;packet size=4096;",
          DB_INIT: |
              docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "MSSQL_PID=Express" -p 1433:1433 -d --name sqlexpress mcr.microsoft.com/mssql/server:2019-latest;
          }
          
          ]              
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.ALLOW_FAILURE == true}}
    env:
      LANG: en-US.UTF-8 #default POSIX locale doesn't support ignore case comparisons
    name: ${{matrix.config.DB}}

    steps:
    - name: Set up ${{matrix.config.DB}}
      run: ${{matrix.config.DB_INIT}}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      run: |
        pwsh -noprofile -command "& ./build.ps1 -TaskList Set-Configuration,Test -properties @{'Database' = '${{matrix.config.DB}}';'ConnectionString'='${{matrix.config.CONNECTION_STRING}}'}"
