name: .NET Core

on: [push, pull_request]

jobs:
  db:
    strategy:
      matrix:
        a: [one, two]
        b:
        - ['1', '2']
        - ['3', '4']
        include:
         c:
         - one
         - two
        exclude:
        - a: two
          b: ['3', '4']
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.ALLOW_FAILURE == true}}
    env:
      LANG: en-US.UTF-8 #default POSIX locale doesn't support ignore case comparisons
    name: ${{matrix.config.DB}}

    steps:
    - name: Set up ${{matrix.config.DB}}
      run: ${{matrix.config.DB_INIT}}
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build and Test
      run: |
        pwsh -noprofile -command "& ./build.ps1 -TaskList Set-Configuration,Test -properties @{'Database' = '${{matrix.config.DB}}';'ConnectionString'='${{matrix.config.CONNECTION_STRING}}'}"
