name: .NET Core

on: [push, pull_request]

jobs:
  db:
    strategy:
      fail-fast: false
      matrix:
        include:
          - DB: SqlServer2008
            CONNECTION_STRING: "Server=localhost;initial catalog=nhibernate;User Id=sa;Password=P@ssw0rd;packet size=4096;"
          - DB: SQLite
    runs-on: windows-latest
    continue-on-error: ${{matrix.ALLOW_FAILURE == true}}
    env:
      LANG: en-US.UTF-8 #default POSIX locale doesn't support ignore case comparisons
    name: ${{matrix.DB}} - Windows

    steps:

    - name: Set up SqlServer Win
      if: matrix.DB == 'SqlServer2008'
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P@ssw0rd" -e "MSSQL_PID=Express" -p 1433:1433 -d --name sqlexpress microsoft/mssql-server-windows-express

    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 2.1.x

    - name: Build and Test
      run: |
        pwsh -noprofile -command "& ./build.ps1 -TaskList Set-Configuration,Test -properties @{'Database' = '${{matrix.DB}}';'ConnectionString'='${{matrix.CONNECTION_STRING}}'}"
