name: Publish Dev Nuget Package

on: [push, pull_request, workflow_dispatch]

jobs:
  publish:
    # if: github.repository == 'nhibernate/nhibernate-core'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          2.2.x
          6.0.x
    - name: Pack
      run: |
        dotnet pack ./src/NHibernate/NHibernate.csproj -m:1 -c Release -p BuildNumber=${{github.run_number}}
    - name: Push to NuGet
      run: dotnet nuget push "./src/NHibernate/bin/Release/*-dev*.nupkg"  --source https://api.nuget.org/v3/index.json
